spring:
  config:
    import:
      - optional:classpath:./secret/db.yml
      - optional:classpath:./secret/aws_s3.yml
      - optional:classpath:./secret/mail.yml
  application:
    name: happygivers
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 20000

mybatis:
  type-aliases-package: com.gitbaby.happygivers.domain
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
